In [1]:
print('hello world!')

hello world!


# Quick Intro

## Python data structure - List

In [5]:
?len

In [2]:
a = [1, 2, 3] 
print(type(a))            # Prints "<class 'list'>"
print(len(a))            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'list'>
3
1 2 3
[5, 2, 3]


## Numpy data structure - ndarray

ndarray = N Dimensional Array

Use ```import``` to call pacakage. call ```numpy```.  np for short.

In [6]:
import numpy as np

call a constant in numpy to see the version of numpy

In [8]:
np.__version__

'1.14.0'

In [9]:
type(np.__version__)

str

np.array() to creat ndarray

In [10]:
?np.array()

In [12]:
a = np.array([1, 2, 3])   # Create a 1d array
a

array([1, 2, 3])

call ndarray's attribute ```shape``` to see the shape 

In [13]:
b = np.array([[1,2,3],[4,5,6]])    # Create a 2d array
print(b.shape)                     # Prints "(2, 3)"

(2, 3)


In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

access certain element

In [15]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

1 2 4


In [2]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


# Creat an array

## Creat an array manually

### 1D  array

In [3]:
a = np.array([0, 1, 2, 3])
print(a)
print(type(a))
print(len(a))
print(a.ndim)
print(a.shape)

[0 1 2 3]
<class 'numpy.ndarray'>
4
1
(4,)


### nD, n>1 multi dimentional array
N = 2, matrix 

In [4]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

print(b)
print(type(b))
print(len(b)) # returns the size of the first dimension
print(b.ndim) 
print(b.shape)

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>
2
2
(2, 3)


N > 2, tensor 

In [5]:
c = np.array([[[1], [2]], [[3], [4]]])
print(c)
print(c.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


## Using functions to creat array

recap: ```range```

In [17]:
r = range(10)
type(r)

range

### Array with equal interval

In [22]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
?np.arange

In [24]:
a = np.arange(10) # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

### Array with specified number of elements

In [8]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [9]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

### help

In [26]:
np.linspace?

In [11]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
b = np.zeros((2, 2))
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [13]:
c = np.eye(3)
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Common data type

In [15]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [27]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

In [28]:
b.itemsize

8

## Using specified data type

In [29]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

In [31]:
c.astype(np.int8).dtype

dtype('int8')

## Default data type is float

In [18]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

## plural, j but not i, which is a convention in engineering

In [19]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

## Boolean

In [20]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

## String

In [21]:
f = np.array(['Bonjour', 'Hello', 'Hallo',])
f.dtype     # <--- strings containing max. 7 letters  

dtype('<U7')

# Indexing and cutting in array

## indexing

In [22]:
a = np.arange(10)
a, a[0], a[2], a[-1]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 0, 2, 9)

reverse

In [23]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [25]:
a[1, 1]

1

In [26]:
a[2, 1] = 10 # third line, second column
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [27]:
a[1]

array([0, 1, 0])

## cutting

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
np.arange(5,15)[[2, 1, 3]]

array([7, 6, 8])

In [37]:
a[np.arange(2,10)]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a[2:9:1] # [start:end:step]

array([2, 3, 4, 5, 6, 7, 8])

### the last indexing is exclusive

In [29]:
a[:4]

array([0, 1, 2, 3])

### by default, start is 0, end is the last and step is 1

In [30]:
a[1:3], a[::2], a[3:]

(array([1, 2]), array([0, 2, 4, 6, 8]), array([3, 4, 5, 6, 7, 8, 9]))

## complex manipulation

In [31]:
a = np.arange(10)
a[5:] = 10
a

b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## exchange two columns

In [52]:
np.array([1,2,3,4])[:]

array([1, 2, 3, 4])

In [43]:
M = np.arange(12).reshape(3,4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

exchange the column 0,1,2,3 to 3,1,2,0

In [44]:
M[:, [3,1,2,0]]

array([[ 3,  1,  2,  0],
       [ 7,  5,  6,  4],
       [11,  9, 10,  8]])

exchange the row 0,1,2 to 2,1,0

In [47]:
M[[2,1,0], :]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [48]:
M[[-1,1,0], :]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

from the ndarray below 
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])``` 

cut and get 
```
array([[ 1,  2],
       [ 5,  6]])``` 


In [54]:
M[:, [1,2]][[0,1], :]

array([[1, 2],
       [5, 6]])

In [59]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

plus 1 to every element in ```list``` ```[0, 1, 2, 3]``` 

In [66]:
l = [0, 1, 2, 3]

ll = []
for x in l:
    ll.append( x + 1)
ll

[1, 2, 3, 4]

In [68]:
[x + 1 for x in l]

[1, 2, 3, 4]

In [65]:
np.array(l) + 1

array([1, 2, 3, 4])

## graph

In [76]:
v = np.arange(0, 51, 10)
v

array([ 0, 10, 20, 30, 40, 50])

In [75]:
v.shape

(6,)

In [78]:
v.reshape(6, 1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [77]:
v[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [79]:
v[np.newaxis, :]

array([[ 0, 10, 20, 30, 40, 50]])

In [81]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [82]:
np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [86]:
[6] + np.arange(0, 51, 10)[:, np.newaxis]

array([[ 6],
       [16],
       [26],
       [36],
       [46],
       [56]])

In [87]:
M = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
M

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

![A small illustrated summary of NumPy indexing and slicing…](numpy_indexing.png "A small illustrated summary of NumPy indexing and slicing…")

In [92]:
M[:2, 2:4]

array([[ 2,  3],
       [12, 13]])

The array above is not equal to the array below (which is the index [0,2], [1,3])

In [93]:
M[[0,1], [2,3]]

array([ 2, 13])

From the second row inclusive, index one time every 2 numbers

In [90]:
M[2::2, :]

array([[20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

From the index.zero column, index one time every 2 numbers

In [89]:
M[:, ::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

## Fancy Indexing

### Boolean Masking

In [33]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [34]:
a % 3 == 0

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False], dtype=bool)

In [35]:
mask = (a % 3 == 0)
a[mask] # or,  a[a%3==0], extract a sub-array with the mask

array([ 3,  0,  9,  6,  0, 12])

### Use array to index array

In [36]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [38]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

![Fancy Indexing](numpy_fancy_indexing.png "Fancy Indexing")