In [1]:
from IPython.core.display import HTML
HTML("""
<style>

        
div.cell { /* Tunes the space between cells */
    margin-top:1em;
    margin-bottom:3em;
}

div.text_cell_render { /* Customize text cells */
    font-family:  Times New Roman, Times, serif;
    font-weight: 500;
    font-size:1.2em;
    line-height:1.2em;
    padding-left:3em;
    padding-right:3em;
}
</style>
""")

# Quick Notes On Matrix Multiplication

## Vector multiplication

$\mathbf{v} = [1, 2, 3], \mathbf{u} = [4, 5, 6]$

$\mathbf{v} \cdot \mathbf{u} = 1 \times 4 + 2 \times 5 + 3 \times 6 = 32$

In [2]:
import numpy as np

v = np.array([1, 2, 3])
u = np.array([4, 5, 6])
v.dot(u)

32

## Matrix and vector multiplication

$\mathbf{X} = \begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix} $

In [3]:
X = np.array([1,2,1,3,8,1,0,4,1]).reshape(3,3)
X

array([[1, 2, 1],
       [3, 8, 1],
       [0, 4, 1]])

### row operations on the left

$
\begin{bmatrix}
1 & 0 & 0 
\end{bmatrix} 
\cdot  
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix} 
= 1 \cdot \begin{bmatrix} 1 & 2 & 1 \end{bmatrix} 
+ 0 \cdot \begin{bmatrix} 3 & 8 & 1 \end{bmatrix} 
+ 0 \cdot \begin{bmatrix} 0 & 4 & 1 \end{bmatrix}
$

combinations of rows of $\mathbf{X}$

In [4]:
np.array([1,0,0]).reshape(1,3).dot(X)

array([[1, 2, 1]])

In [5]:
np.array([3,4,5]).dot(X)

array([15, 58, 12])

### column operations on the right

$
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix}
\cdot  
\begin{bmatrix}
1 & 0 & 0 \\
\end{bmatrix}
= 1 \cdot \begin{bmatrix} 1 \\ 3 \\ 0 \end{bmatrix} 
+ 0 \cdot \begin{bmatrix} 2 \\ 8 \\ 4 \end{bmatrix} 
+ 0 \cdot \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix} 
$

combinations of columns of $\mathbf{X}$

In [6]:
X.dot(np.array([1,0,0]).reshape(3,1))

array([[1],
       [3],
       [0]])

In [7]:
X.dot(np.array([3,4,5]))

array([16, 46, 21])

## Matrix multiplication
### identity matrix
$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix} 
=
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix}
\cdot  
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
= \begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix}
$

In [8]:
np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3).dot(X)

array([[1, 2, 1],
       [3, 8, 1],
       [0, 4, 1]])

In [9]:
X.dot(np.array([0,0,1,0,1,0,1,0,0]).reshape(3,3))

array([[1, 2, 1],
       [1, 8, 3],
       [1, 4, 0]])

### matrix mutiplies matrix

<img src="matmul.png">

$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix} 
=
\begin{bmatrix}
7 & 30 & 6 \\
19 & 72 & 15 \\
31 & 114 & 24
\end{bmatrix}
$


In [10]:
Y = np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
Y.dot(X)

array([[  7,  30,   6],
       [ 19,  72,  15],
       [ 31, 114,  24]])

## Inverse

Find inverse of $\mathbf{A}$ with Gauss-Jodan method 

let $\mathbf{A}$ be 

$\begin{bmatrix}
1 & 3 \\
2 & 7
\end{bmatrix}$

construct the augmented matrix $<\mathbf{A}|\mathbf{I}>$:

$\left[
\begin{array}{rr|rr}
1 & 3 & 1 & 0\\
2 & 7 & 0 & 1
\end{array}
\right]$

keep eliminating $<\mathbf{A}|\mathbf{I}>$ until the left matrix is identity:

$\left[
\begin{array}{rr|rr}
1 & 0 & 7 & -3\\
0 & 1 & -2 & 1
\end{array}
\right]$

thus $\mathbf{A}^{-1}$ is:

$\left[
\begin{array}{rr}
7 & -3\\
-2 & 1
\end{array}
\right]$

suppose the elimination matrix is $\mathbf{E}$ such that $\mathbf{E} \mathbf{A} = \mathbf{I}$, then $\mathbf{E} = \mathbf{A}^{-1}$

to make the left matrix in $<\mathbf{A}|\mathbf{I}>$ an indentity matrix, multiply $\mathbf{E}$ to the left:

$\mathbf{E} <\mathbf{A}|\mathbf{I}> = <\mathbf{I}|\mathbf{A}^{-1}>$ 

In [12]:
Y = np.array([1,3,1,0,2,7,0,1]).reshape(2,4)
Y

array([[1, 3, 1, 0],
       [2, 7, 0, 1]])

In [13]:
Y2 = np.array([1,0,-2,1]).reshape(2,2).dot(Y)
Y2

array([[ 1,  3,  1,  0],
       [ 0,  1, -2,  1]])

In [14]:
Y3 = np.array([1,-3,0,1]).reshape(2,2).dot(Y2)
Y3

array([[ 1,  0,  7, -3],
       [ 0,  1, -2,  1]])

In [15]:
E = np.array([1,-3,0,1]).reshape(2,2).dot(np.array([1,0,-2,1]).reshape(2,2))
E

array([[ 7, -3],
       [-2,  1]])