# Euclidean Distance

Given a Cartesian coordinate system, the Eculidean distance between two vectors $\textbf{u}$ and $\textbf{v}$ is defined as: <br>


\begin{equation}
d(\textbf{u}, \textbf{v}) = d(\textbf{v}, \textbf{u}) = \sqrt{\sum_{i=1}^{n} (\textbf{u}_i - \textbf{v}_i)^2}
\end{equation} <br>

This is also known as $\ell^2$ distance between $\textbf{u}$ and $\textbf{v}$, or the $\ell^2$-norm of $\textbf{u} - \textbf{v}$:<br>

\begin{equation}
\| \textbf{u} - \textbf{v} \|_2
\end{equation} <br>

Implement Euclidean distance with Numpy

In [3]:
import math
u = [1, 2, 3]
v = [4, 5, 6]

squared_sum = 0
for u_i, v_i in zip(u, v):
    squared_sum += (u_i - v_i) ** 2

math.sqrt(squared_sum)

5.196152422706632

$\sqrt{(\mathbf{u} - \mathbf{v}) \cdot (\mathbf{u} - \mathbf{v})}$

In [6]:
import numpy as np
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
np.sqrt((u - v).dot(u - v))

5.196152422706632

Note, in ```numpy```, ```*``` gives element-wise multiplication, which is **not** the matrix/vector multiplication as we known as dot product.

avilable only to ```numpy.ndarray```

In [7]:
u * v

array([ 4, 10, 18])

In [8]:
u ** 2

array([1, 4, 9], dtype=int32)

element-wise square of every element in vector $\mathbf{u} - \mathbf{v}$

In [9]:
(u - v) ** 2

array([9, 9, 9], dtype=int32)

square root of sum of all elements in ```(u - v) ** 2```

In [12]:
np.sqrt(np.sum((u - v) ** 2))

5.196152422706632

In [3]:
import numpy as np
def euclidean_dist(u, v):
    # write your code here
    u, v = np.array(u), np.array(v)
    # return
    pass
    return np.sqrt(np.sum((u - v) ** 2))

如果实现正确, 运行下方代码时不应该出现 AssertionError

In [4]:
import numpy as np
from scipy.spatial.distance import euclidean
for _ in range(10):
    u = np.random.rand(50)
    v = np.random.rand(50)
    assert np.isclose(euclidean_dist(u, v), np.linalg.norm(u - v))
    assert np.isclose(euclidean_dist(u, v), euclidean(u, v))
print('Your implementation is correct.')

Your implementation is correct.


In [16]:
?np.isclose